apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # these lables are replica set lables
  labels:
    project: roboshop
    tier: database
    component: mongodb
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
  # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: database
      component: mongodb
# This is pod definition. pod is subset of replica set
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}