apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue

data:
  MONGO: "true"
  MONGO_URL: {{ .Values.configmap.MONGO_URL }}